dist: trusty
sudo: required
language: go

go:
- 1.9.x
- 1.10.x

env:
- MYSQL_IMAGE=library/mariadb:10.1

services:
- docker

go_import_path: github.com/percona/mysqld_exporter

before_script:
- sudo service mysql stop
- docker --version
- docker-compose --version
- docker-compose up -d

script:
- make
- make test

notifications:
  email: false
